#!/bin/bash
echo "[+] Installing XFCE4, this will take a while"
sudo apt update
sudo apt full-upgrade -y
sudo apt install -y kali-desktop-xfce xorg xrdp compton
echo "[+] Configuring XRDP to listen on port 3390 (but not starting the service)..."
sudo sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
echo "[+] Adding some settings to ~./bashrc"
echo '## enable xcfe launch in WSL
export DISPLAY=:0
export XDG_RUNTIME_DIR=~/runtime
export RUNLEVEL=3
LANG="en_US.utf8"' >> ~/.bashrc
sudo echo '## enable xcfe launch in WSL
export DISPLAY=:0
export XDG_RUNTIME_DIR=~/runtime
export RUNLEVEL=3
LANG="en_US.utf8"' >> /root/.bashrc
echo "[+] Getting some more scripts"
wget -O ~/start-xfce https://raw.githubusercontent.com/Re4son/WSL-Kali-X/master/start-xfce
wget -O ~/.xinitrc https://raw.githubusercontent.com/Re4son/WSL-Kali-X/master/.xinitrc
ln -s ~/.xinitrc ~/.xsession
sudo cp ~/.xinitrc start-xfce /root/
sudo chown root:root /root/.xinitrc /root/start-xfce
sudo chmod 755 /root/.xinitrc /root/start-xfce
sudo ln -s /root/.xinitrc /root/.xsession
echo "[+] Changing default panel settings for xfce"
sudo wget -O /etc/xdg/xfce4/panel/default.xml https://raw.githubusercontent.com/Re4son/WSL-Kali-X/master/default.xml
sudo wget -O /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml https://raw.githubusercontent.com/Re4son/WSL-Kali-X/master/xfce4-session.xml
echo
echo
echo "[*] This part of the installation is completed. Only one more thing to do:"
echo
echo "[*] Please download and install VcXsrv X Server from here:"
echo "    https://sourceforge.net/projects/vcxsrv/"
echo
echo
echo "[*] You can start WSL Kali-X via:"
echo "    ~/start-xfce            #(as normal user)"
echo "    sudo /root/start-xfce   #(as root user)"
